--[[
    Template for the Main menu
    It also dictates which button does what, sort of speak
    This way, it will be easier to do custom menus
    You can simply make a new menu and then link it to the preceding item you want it to be
]]
local menu = {
    main = {        --MAIN MENU
    
    },
    play = {        --PLAY SECTION

    },
    settings = {    --SETTINGS

    },
    more = {        --CONTACT US & MORE

    }
}
return menu